FROM python:3.11

# Steps are cached with Kaniko in GCP Artifcat registry
# The cache is kept 72 hours (see cloudbuild.yaml)

WORKDIR /src
RUN pip install poetry

# Copy pyproject.toml and poetry.lock
COPY ./pyproject.toml /src/pyproject.toml
COPY ./poetry.lock /src/poetry.lock

# Install dependencies
RUN poetry config virtualenvs.create false

# We do not copy the phospho python package, instead we install it from pip, we do not use --with dev
RUN poetry install --no-interaction --no-ansi
RUN poetry run pip install phospho[lab]

# Copy source code
COPY ./phospho_backend /src/phospho_backend

# Run the server on port 80
CMD ["uvicorn", "phospho_backend.main:app", "--host", "0.0.0.0", "--port", "80"]