options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: portal-385519
steps:
  # Doc : https://github.com/GoogleContainerTools/kaniko
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=europe-west1-docker.pkg.dev/portal-385519/phospho-extractor/app:staging
      - --cache=true
      - --cache-ttl=72h # Expiration time of the cache. This means dependencies will be cached for 72 hours.
      - --dockerfile=/extractor/Dockerfile
