FROM python:3.11

# Steps are cached with Kaniko in GCP Artifcat registry
# The cache is kept 72 hours (see cloudbuild.yaml)

WORKDIR /src
RUN pip install poetry

# Copy pyproject.toml and poetry.lock
COPY ./pyproject.toml /src/pyproject.toml
COPY ./poetry.lock /src/poetry.lock

# Install dependencies
RUN poetry config virtualenvs.create false

# Install phospho package
RUN poetry install --no-interaction --no-ansi
RUN poetry run pip install --upgrade phospho[lab]

# Copy source code
COPY ./extractor /src/extractor
COPY ./main.py /src/main.py

# Run the server on port 80
CMD ["poetry", "run", "python", "main.py"]
