"use client";

import { Spinner } from "@/components/small-spinner";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { useToast } from "@/components/ui/use-toast";
import { authFetcher } from "@/lib/fetcher";
import {
  DetectionScope,
  EventDefinition,
  Project,
  ScoreRangeType,
} from "@/models/models";
import { navigationStateStore } from "@/store/store";
import { useUser } from "@propelauth/nextjs/client";
import { TestTubeDiagonal } from "lucide-react";
import { useRouter } from "next/navigation";
import { sendUserFeedback } from "phospho";
import { useEffect, useState } from "react";
import useSWR from "swr";

function EventDisplay({
  eventDefintion,
  onToggle,
  isSelected,
}: {
  eventDefintion: EventDefinition;
  onToggle: () => void;
  isSelected: boolean;
}) {
  // This is a single component that displays an event definition
  // It also has a tickbox to enable or disable the event for the project
  return (
    <Card className="text-wrap">
      <CardHeader className="pb-2">
        <div className="flex flex-row items-center space-x-4">
          <Checkbox
            className="h-8 w-8"
            onClick={onToggle}
            checked={isSelected}
          />
          <CardTitle>{eventDefintion.event_name}</CardTitle>
        </div>
      </CardHeader>
      <CardContent>
        <CardDescription>{eventDefintion.description}</CardDescription>
      </CardContent>
    </Card>
  );
}

const dummyEventDefinitions: EventDefinition[] = [];

export default function AddEvents({
  project_id,
  phosphoTaskId,
  redirectTo = "/onboarding/plan",
}: {
  project_id: string;
  phosphoTaskId: string | null;
  redirectTo?: string;
}) {
  const router = useRouter();
  const selectedOrgId = navigationStateStore((state) => state.selectedOrgId);
  const { loading, accessToken } = useUser();
  const { toast } = useToast();

  const { data: selectedProject }: { data: Project } = useSWR(
    project_id ? [`/api/projects/${project_id}`, accessToken] : null,
    ([url, accessToken]) => authFetcher(url, accessToken, "GET"),
    {
      keepPreviousData: true,
    },
  );

  const getEventsFromTemplateName = (templateName: string) => {
    /*
     * Return a list of event definitions based on the template name
     */

    let events;
    const eventBase = {
      org_id: selectedOrgId,
      project_id: project_id,
    };
    const soundsRobotic = {
      ...eventBase,
      event_name: "Sounds robotic",
      description: "The text generated by the assistant sounds robotic.",
      detection_scope: DetectionScope.TaskOutputOnly,
    };
    const verbose = {
      ...eventBase,
      event_name: "Verbose",
      description:
        "The assistant has generated repetitive text or text too long and boring.",
      detection_scope: DetectionScope.TaskOutputOnly,
    };
    const userSentiment = {
      ...eventBase,
      event_name: "User sentiment",
      description:
        "Rate the sentiment of the user input. 1 is negative (sad, frustrated, confused), 5 is positive (happy, satisfied).",
      detection_scope: DetectionScope.TaskInputOnly,
      score_range_settings: {
        min: 1,
        max: 5,
        score_type: ScoreRangeType.range,
        categories: [],
      },
    };
    const toxicContent = {
      ...eventBase,
      event_name: "Toxic content",
      description: "The assistant has generated curse words or toxic content.",
      detection_scope: DetectionScope.TaskOutputOnly,
    };
    const penetrationTesting = {
      ...eventBase,
      event_name: "Penetration testing",
      description: "The user is trying to jailbreak the LLM app.",
      detection_scope: DetectionScope.TaskInputOnly,
    };
    const humanRequest = {
      ...eventBase,
      event_name: "Ask human",
      description:
        "The user is asking to talk to a human, a real person, or an actual operator.",
      detection_scope: DetectionScope.TaskInputOnly,
    };
    const successFullSession = {
      ...eventBase,
      event_name: "Solved the problem",
      description:
        "The conversaiton was successful for the end user. The user acknowledged that the problem was solved.",
      detection_scope: DetectionScope.Session,
    };
    const upsell = {
      ...eventBase,
      event_name: "Up-sell",
      description:
        "The assistant has generated a response that tries to upsell a product or service.",
      detection_scope: DetectionScope.Task,
    };
    const answeredQuestion = {
      ...eventBase,
      event_name: "Answered question",
      description:
        "The assistant has generated a response that answers a question. The user acknowledged that the question was answered.",
      detection_scope: DetectionScope.Session,
    };
    const citedSource = {
      ...eventBase,
      event_name: "Sourced",
      description:
        "The assistant has generated a response that cites a source or references a website.",
      detection_scope: DetectionScope.TaskOutputOnly,
    };
    const userIndustry = {
      ...eventBase,
      event_name: "User industry",
      description:
        "The user has mentioned an industry or is asking a question only relevant for a specific industry.",
      detection_scope: DetectionScope.TaskInputOnly,
      score_range_settings: {
        score_type: ScoreRangeType.category,
        categories: [
          "Technology",
          "Finance",
          "Healthcare",
          "Education",
          "Retail",
          "Manufacturing",
          "Entertainment",
          "Government",
        ],
      },
    };
    const userJobTitle = {
      ...eventBase,
      event_name: "User job title",
      description:
        "The user has mentioned his or her job title. The user is asking a question which is especially relevant for a specific job title.",
      detection_scope: DetectionScope.TaskInputOnly,
      score_range_settings: {
        score_type: ScoreRangeType.category,
        categories: [
          "Software Engineer",
          "Doctor",
          "Teacher",
          "Salesperson",
          "Executive",
          "Student",
          "Journalist",
          "Economist",
          "Artist",
        ],
      },
    };
    const productLine = {
      ...eventBase,
      event_name: "Product category",
      description:
        "The user has mentioned a product from a specific cateogory, or which is only relevant for this product category.",
      detection_scope: DetectionScope.TaskInputOnly,
      score_range_settings: {
        score_type: ScoreRangeType.category,
        categories: [
          "Electronics",
          "Fashion",
          "Automotive",
          "Food",
          "Books",
          "Furniture",
          "Entertainment",
        ],
      },
    };

    if (templateName === "Text generation") {
      events = [soundsRobotic, verbose, userSentiment, toxicContent];
    }
    if (templateName === "Sales assistant") {
      events = [
        upsell,
        productLine,
        userJobTitle,
        userIndustry,
        userSentiment,
        penetrationTesting,
        verbose,
        toxicContent,
        soundsRobotic,
      ];
    }
    if (templateName === "Customer support") {
      events = [
        successFullSession,
        humanRequest,
        userJobTitle,
        userIndustry,
        userSentiment,
        penetrationTesting,
        toxicContent,
        verbose,
      ];
    }
    if (templateName === "Knowledge assistant") {
      events = [
        answeredQuestion,
        citedSource,
        userJobTitle,
        userIndustry,
        userSentiment,
        soundsRobotic,
        verbose,
      ];
    }

    return events as EventDefinition[];
  };

  const [sendEventsLoading, setSendEventsLoading] = useState(false);
  const [customEvents, setCustomEvents] = useState<EventDefinition[] | null>(
    null,
  );
  const [isSelected, setIsSelected] = useState<{ [key: string]: boolean }>(
    dummyEventDefinitions?.reduce(
      (acc, eventDefintion) => ({
        ...acc,
        [eventDefintion.event_name]: false,
      }),
      {},
    ),
  );

  useEffect(() => {
    if (customEvents) {
      setIsSelected(
        customEvents.reduce(
          (acc, eventDefintion) => ({
            ...acc,
            [eventDefintion.event_name]: true,
          }),
          {},
        ),
      );
    }
  }, [customEvents]);

  useEffect(() => {
    if (selectedOrgId && customEvents === null) {
      setCustomEvents(getEventsFromTemplateName("Knowledge assistant"));
    }
  }, [selectedOrgId]);

  const handleToggle = (eventName: string) => {
    setIsSelected((prevIsSelected) => ({
      ...prevIsSelected,
      [eventName]: !prevIsSelected[eventName],
    }));
  };

  const saveSelectedEvents = async () => {
    const selectedEvents = Object.entries(isSelected)
      ?.filter(([_key, value]) => value)
      ?.map(([key, _value]) => key);
    // Now get the full events from custom events
    // and save the selected events to the project
    const selectedEventDefinitions = customEvents?.filter((eventDefintion) =>
      selectedEvents.includes(eventDefintion.event_name),
    );
    console.log("Selected Event Definitions:", selectedEventDefinitions);

    const response = await fetch(`/api/projects/${project_id}/add-events`, {
      method: "POST",
      headers: {
        Authorization: "Bearer " + accessToken,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        // provide a list of the selected events in customEvents
        events: selectedEventDefinitions,
      }),
    });
    if (phosphoTaskId !== null) {
      try {
        sendUserFeedback({
          taskId: phosphoTaskId,
          projectId: "b20659d0932d4edbb2b9682d3e6a0ccb",
          flag:
            (selectedEventDefinitions?.length ?? 0) > 0 ? "success" : "failure",
          source: "user",
          notes: `Selected ${
            selectedEventDefinitions?.length ?? 0
          } events: ${selectedEventDefinitions
            ?.map((event) => event.event_name)
            .join(", ")}`,
        });
      } catch (e) {
        console.error("Error sending feedback to Phospho", e);
      }
    } else {
      console.error("Phospho task_id is null");
    }
  };

  return (
    <>
      <Card className="w-1/2">
        <CardHeader>
          <CardTitle className="flex items-end">
            <TestTubeDiagonal className="w-8 h-8 mr-2 text-green-500" />
            Select an analytics starter for the project{" "}
            {selectedProject?.project_name ?? ""}
          </CardTitle>
          <CardDescription>
            phospho runs automated analytics to augment your data with tags,
            scores, and labels.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col space-y-2 border-muted-foreground">
          <div className="flex justify-center align-items">
            <ToggleGroup
              type="single"
              defaultValue="Knowledge assistant"
              variant="outline"
            >
              <ToggleGroupItem
                value="Knowledge assistant"
                onClick={() =>
                  setCustomEvents(
                    getEventsFromTemplateName("Knowledge assistant"),
                  )
                }
              >
                Knowledge assistant
              </ToggleGroupItem>
              <ToggleGroupItem
                value="Sales assistant"
                onClick={() =>
                  setCustomEvents(getEventsFromTemplateName("Sales assistant"))
                }
              >
                Sales assistant
              </ToggleGroupItem>
              <ToggleGroupItem
                value="Customer support"
                onClick={() =>
                  setCustomEvents(getEventsFromTemplateName("Customer support"))
                }
              >
                Customer support
              </ToggleGroupItem>
            </ToggleGroup>
          </div>
          <div className="flex flex-col space-y-2 overflow-y-auto h-96">
            {customEvents &&
              customEvents?.map &&
              customEvents?.map((eventDefinition) => (
                <EventDisplay
                  eventDefintion={eventDefinition}
                  key={eventDefinition.event_name}
                  onToggle={() => handleToggle(eventDefinition.event_name)}
                  isSelected={isSelected[eventDefinition.event_name]}
                />
              ))}
          </div>
          <div className="text-muted-foreground text-sm">
            You can change this later in the Analytics section.
          </div>
        </CardContent>
        <CardFooter>
          <Button
            className="w-full"
            onClick={async () => {
              setSendEventsLoading(true);
              saveSelectedEvents().then((response) => {
                router.push(redirectTo);
                toast({
                  title: "Your config has been saved! 🎉",
                  description: `Change the config in Analytics`,
                });
              });
            }}
            disabled={loading || customEvents === null}
          >
            {sendEventsLoading && <Spinner className="mr-1" />}
            Save and continue
          </Button>
        </CardFooter>
      </Card>
    </>
  );
}
