name: documentation

on:
  workflow_dispatch:
  push:
    paths:
      - "phospho-python/**"
    branches:
      - dev
      - main
  release:
    types: [released]

permissions:
  contents: write

jobs:
  build_phospho_python_doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phospho-python
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      # Install dependencies if cache does not exist
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --with docs,dev --extras "lab" --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction --extras "lab"

      - name: Sphinx build
        run: |
          source .venv/bin/activate
          cd docs
          make clean
          sphinx-build source _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        # The build files will be located on branch gh-pages
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
