# This workflow will upload a Python Package using Poetry
name: Publish to PyPI

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish_phospho_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phospho-python
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Poetry add token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Build
        run: poetry build

      - name: Publish
        run: poetry publish
